sudo: required
services:
  - docker

language: rust
rust:
  - nightly
cache: cargo

install:
  - mdbook -V || cargo install mdbook --vers "^0.2.0"
script: >
  mdbook build &&
  mdbook test &&
  docker run --rm --tty --volume "$PWD:/app/" --workdir /app/ microsoft/dotnet:2.1-sdk \
    dotnet run --configuration Release --project "test\ReferenceValidator\ReferenceValidator.csproj"

deploy:
  provider: pages
  local-dir: book
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master

notifications:
  email:
    on_success: never
    on_failure: always

## Notes:
### Limit concurrent jobs to only 1
### Disable building PRs (might expose environment variables)
