[book]
authors = ["Poulad Ashrafpour", "Aleksey Usatov", "karb0f0s", "Miha Zupan", "Wizou"]
multilingual = false
src = "src"
title = "A guide to Telegram.Bot library"
site-url = "https://telegrambots.github.io/book/"
language = "en"
output.html.fold.enable = true

[output.html]
git-repository-url = "https://github.com/TelegramBots/book"
additional-css = ["theme/custom.css"]

[preprocessor.alerts]

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
