[book]
authors = ["Poulad Ashrafpour", "Aleksey Usatov", "karb0f0s", "Miha Zupan"]
multilingual = false
src = "src"
title = "A guide to Telegram.Bot library"
site-url = "https://telegrambots.github.io/book/"
language = "en"

[output.html]
git-repository-url = "https://github.com/TelegramBots/book"
additional-css = ["custom.css"]
